### ISSUE TITLE
Difference between 2 Character folders?

### ISSUE THREAD

**Issue by JonathanEspinosaLong** [justinwasilenko/Unity-Style-Guide#3]
Hey, I really like the work you've put into this. I'll be using it as a base for my next project. I am just curious as to what the difference is between the Characters folder in the Project directory and the Characters folder in the Gameplay directory. If you could clear that up I'd really appreciate it.

**Comment by justinwasilenko** [comment]
Sorry that was a mistake, I just use the main Characters folder, not one under the Gameplay folder.

I have been making some changes over the course of my project but haven't commited them yet.
