### ISSUE TITLE
Dead "Unity Audio Import Optimization" link

### ISSUE THREAD

**Issue by bulleador** [justinwasilenko/Unity-Style-Guide#5]
[Unity Audio Import Optimization](https://www.gamasutra.com/blogs/ZanderHulme/20190107/333794/Unity_Audio_Import_Optimisation__getting_more_BAM_for_your_RAM.php) url located [here](https://github.com/justinwasilenko/Unity-Style-Guide/blob/3f8d9fdf6b4e1beb94c27abb20d44340c90aaff1/README.md?plain=1#L1148C3-L1148C3) seems to be dead (403 Forbidden). 

[This article](https://www.gamedeveloper.com/audio/unity-audio-import-optimisation---getting-more-bam-for-your-ram) is probably the same one.

**Comment by bulleador** [comment]
Sorry, all is well. Must've been an issue on my side

**Comment by justinwasilenko** [comment]
I will update link, Gamasutra changed there domain and didn't forward all links yet.
